<?php

use Illuminate\Database\Seeder;


/**
 * Class CodesTableSeeder
 * https://laravel.com/docs/5.1/migrations#running-migrations
 * http://genealogy.about.com/library/weekly/aa110100d.htm
 */

class CodesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Eloquent::unguard();

        DB::table('codes')->insert(array(
            array('code'=>'ABBR','name'=>'ABBREVIATION','description'=>'A short name of a title, description, or name.'),
            array('code'=>'ADDR','name'=>'ADDRESS','description'=>'The contemporary place, usually required for postal purposes, of an individual, a submitter of information, a repository, a business, a school, or a company.'),
            array('code'=>'ADR1','name'=>'ADDRESS1','description'=>'The first line of an address.'),
            array('code'=>'ADR2','name'=>'ADDRESS2','description'=>'The second line of an address.'),
            array('code'=>'ADOP','name'=>'ADOPTION','description'=>'Pertaining to creation of a child-parent relationship that does not exist biologically.'),
            array('code'=>'AFN','name'=>'AFN','description'=>'A unique permanent record file number of an individual record stored in Ancestral File.'),
            array('code'=>'AGE','name'=>'AGE','description'=>'The age of the individual at the time an event occurred, or the age listed in the document.'),
            array('code'=>'AGNC','name'=>'AGENCY','description'=>'The institution or individual having authority and/or responsibility to manage or govern.'),
            array('code'=>'ALIA','name'=>'ALIAS','description'=>'An indicator to link different record descriptions of a person who may be the same person.'),
            array('code'=>'ANCE','name'=>'ANCESTORS','description'=>'Pertaining to forbearers of an individual.'),
            array('code'=>'ANCI','name'=>'ANCES_INTEREST','description'=>'Indicates an interest in additional research for ancestors of this individual. (See also DESI)'),
            array('code'=>'ANUL','name'=>'ANNULMENT','description'=>'Declaring a marriage void from the beginning (never existed).'),
            array('code'=>'ASSO','name'=>'ASSOCIATES','description'=>'An indicator to link friends, neighbors, relatives, or associates of an individual.'),
            array('code'=>'AUTH','name'=>'AUTHOR','description'=>'The name of the individual who created or compiled information.'),
            array('code'=>'BAPL','name'=>'BAPTISM-LDS','description'=>'The event of baptism performed at age eight or later by priesthood authority of the LDS Church. (See also BAPM, next)'),
            array('code'=>'BAPM','name'=>'BAPTISM','description'=>'The event of baptism (not LDS), performed in infancy or later. (See also BAPL, above, and CHR, page 73.)'),
            array('code'=>'BARM','name'=>'BAR_MITZVAH','description'=>'The ceremonial event held when a Jewish boy reaches age 13.'),
            array('code'=>'BASM','name'=>'BAS_MITZVAH','description'=>'The ceremonial event held when a Jewish girl reaches age 13, also known as "Bat Mitzvah."'),
            array('code'=>'BIRT','name'=>'BIRTH','description'=>'The event of entering into life.'),
            array('code'=>'BLES','name'=>'BLESSING','description'=>'A religious event of bestowing divine care or intercession. Sometimes given in connection with a naming ceremony.'),
            array('code'=>'BLOB','name'=>'BINARY_OBJECT','description'=>'A grouping of data used as input to a multimedia system that processes binary data to represent images, sound, and video.'),
            array('code'=>'BURI','name'=>'BURIAL','description'=>'The event of the proper disposing of the mortal remains of a deceased person.'),
            array('code'=>'CALN','name'=>'CALL_NUMBER','description'=>'The number used by a repository to identify the specific items in its collections.'),
            array('code'=>'CAST','name'=>'CASTE','description'=>'The name of an individual\'s rank or status in society, based on racial or religious differences, or differences in wealth, inherited rank, profession, occupation, etc.'),
            array('code'=>'CAUS','name'=>'CAUSE','description'=>'A description of the cause of the associated event or fact, such as the cause of death.'),
            array('code'=>'CENS','name'=>'CENSUS','description'=>'The event of the periodic count of the population for a designated locality, such as a national or state Census.'),
            array('code'=>'CHAN','name'=>'CHANGE','description'=>'Indicates a change, correction, or modification. Typically used in connection with a DATE to specify when a change in information occurred.'),
            array('code'=>'CHAR','name'=>'CHARACTER','description'=>'An indicator of the character set used in writing this automated information.'),
            array('code'=>'CHIL','name'=>'CHILD','description'=>'The natural, adopted, or sealed (LDS) child of a father and a mother.'),
            array('code'=>'CHR','name'=>'CHRISTENING','description'=>'The religious event (not LDS) of baptizing and/or naming a child.'),
            array('code'=>'CHRA','name'=>'ADULT_CHRISTENING','description'=>'The religious event (not LDS) of baptizing and/or naming an adult person.'),
            array('code'=>'CITY','name'=>'CITY','description'=>'A lower level jurisdictional unit. Normally an incorporated municipal unit.'),
            array('code'=>'CONC','name'=>'CONCATENATION','description'=>'An indicator that additional data belongs to the superior value. The information from the CONC value is to be connected to the value of the superior preceding line without a space and without a carriage return and/or new line character. Values that are split for a CONC tag must always be split at a non-space. If the value is split on a space the space will be lost when concatenation takes place. This is because of the treatment that spaces get as a GEDCOM delimiter, many GEDCOM values are trimmed of trailing spaces and some systems look for the first non-space starting after the tag to determine the beginning of the value.'),
            array('code'=>'CONF','name'=>'CONFIRMATION','description'=>'The religious event (not LDS) of conferring the gift of the Holy Ghost and, among protestants, full church membership.'),
            array('code'=>'CONL','name'=>'CONFIRMATION_L','description'=>'The religious event by which a person receives membership in the LDS Church.'),
            array('code'=>'CONT','name'=>'CONTINUED','description'=>'An indicator that additional data belongs to the superior value. The information from the CONT value is to be connected to the value of the superior preceding line with a carriage return and/or new line character. Leading spaces could be important to the formatting of the resultant text. When importing values from CONT lines the reader should assume only one delimiter character following the CONT tag. Assume that the rest of the leading spaces are to be a part of the value.'),
            array('code'=>'COPR','name'=>'COPYRIGHT','description'=>'A statement that accompanies data to protect it from unlawful duplication and distribution.'),
            array('code'=>'CORP','name'=>'CORPORATE','description'=>'A name of an institution, agency, corporation, or company.'),
            array('code'=>'CREM','name'=>'CREMATION','description'=>'Disposal of the remains of a person\'s body by fire.'),
            array('code'=>'CTRY','name'=>'COUNTRY','description'=>'The name or code of the country.'),
            array('code'=>'DATA','name'=>'DATA','description'=>'Pertaining to stored automated information.'),
            array('code'=>'DATE','name'=>'DATE','description'=>'The time of an event in a calendar format.'),
            array('code'=>'DEAT','name'=>'DEATH','description'=>'The event when mortal life terminates.'),
            array('code'=>'DESC','name'=>'DESCENDANTS','description'=>'Pertaining to offspring of an individual.'),
            array('code'=>'DESI','name'=>'DESCENDANT_INT','description'=>'Indicates an interest in research to identify additional descendants of this individual. (See also ANCI)'),
            array('code'=>'DEST','name'=>'DESTINATION','description'=>'A system receiving data.'),
            array('code'=>'DIV','name'=>'DIVORCE','description'=>'An event of dissolving a marriage through civil action.'),
            array('code'=>'DIVF','name'=>'DIVORCE_FILED','description'=>'An event of filing for a divorce by a spouse.'),
            array('code'=>'DSCR','name'=>'PHY_DESCRIPTION','description'=>'The physical characteristics of a person, place, or thing.'),
            array('code'=>'EDUC','name'=>'EDUCATION','description'=>'Indicator of a level of education attained.'),
            array('code'=>'EMIG','name'=>'EMIGRATION','description'=>'An event of leaving one\'s homeland with the intent of residing elsewhere.'),
            array('code'=>'ENDL','name'=>'ENDOWMENT','description'=>'A religious event where an endowment ordinance for an individual was performed by priesthood authority in an LDS temple.'),
            array('code'=>'ENGA','name'=>'ENGAGEMENT','description'=>'An event of recording or announcing an agreement between two people to become married.'),
            array('code'=>'EVEN','name'=>'EVENT','description'=>'A noteworthy happening related to an individual, a group, or an organization.'),
            array('code'=>'FAM','name'=>'FAMILY','description'=>'Identifies a legal, common law, or other customary relationship of man and woman and their children, if any, or a family created by virtue of the birth of a child to its biological father and mother.'),
            array('code'=>'FAMC','name'=>'FAMILY_CHILD','description'=>'Identifies the family in which an individual appears as a child.'),
            array('code'=>'FAMF','name'=>'FAMILY_FILE','description'=>'Pertaining to, or the name of, a family file. Names stored in a file that are assigned to a family for doing temple ordinance work.'),
            array('code'=>'FAMS','name'=>'FAMILY_SPOUSE','description'=>'Identifies the family in which an individual appears as a spouse.'),
            array('code'=>'FCOM','name'=>'FIRST_COMMUNION','description'=>'A religious rite, the first act of sharing in the Lord\'s supper as part of church worship.'),
            array('code'=>'FILE','name'=>'FILE','description'=>'An information storage place that is ordered and arranged for preservation and reference.'),
            array('code'=>'FORM','name'=>'FORMAT','description'=>'An assigned name given to a consistent format in which information can be conveyed.'),
            array('code'=>'GEDC','name'=>'GEDCOM','description'=>'Information about the use of GEDCOM in a transmission.'),
            array('code'=>'GIVN','name'=>'GIVEN_NAME','description'=>'A given or earned name used for official identification of a person.'),
            array('code'=>'GRAD','name'=>'GRADUATION','description'=>'An event of awarding educational diplomas or degrees to individuals.'),
            array('code'=>'HEAD','name'=>'HEADER','description'=>'Identifies information pertaining to an entire GEDCOM transmission.'),
            array('code'=>'HUSB','name'=>'HUSBAND','description'=>'An individual in the family role of a married man or father.'),
            array('code'=>'IDNO','name'=>'IDENT_NUMBER','description'=>'A number assigned to identify a person within some significant external system.'),
            array('code'=>'IMMI','name'=>'IMMIGRATION','description'=>'An event of entering into a new locality with the intent of residing there.'),
            array('code'=>'INDI','name'=>'INDIVIDUAL','description'=>'A person.'),
            array('code'=>'INFL','name'=>'TempleReady','description'=>'Indicates if an INFANT - data is "Y" (or "N"??)'),
            array('code'=>'LANG','name'=>'LANGUAGE','description'=>'The name of the language used in a communication or transmission of information.'),
            array('code'=>'LEGA','name'=>'LEGATEE','description'=>'A role of an individual acting as a person receiving a bequest or legal devise.'),
            array('code'=>'MARB','name'=>'MARRIAGE_BANN','description'=>'An event of an official public notice given that two people intend to marry.'),
            array('code'=>'MARC','name'=>'MARR_CONTRACT','description'=>'An event of recording a formal agreement of marriage, including the prenuptial agreement in which marriage partners reach agreement about the property rights of one or both, securing property to their children.'),
            array('code'=>'MARL','name'=>'MARR_LICENSE','description'=>'An event of obtaining a legal license to marry.'),
            array('code'=>'MARR','name'=>'MARRIAGE','description'=>'A legal, common-law, or customary event of creating a family unit of a man and a woman as husband and wife.'),
            array('code'=>'MARS','name'=>'MARR_SETTLEMENT','description'=>'An event of creating an agreement between two people contemplating marriage, at which time they agree to release or modify property rights that would otherwise arise from the marriage.'),
            array('code'=>'MEDI','name'=>'MEDIA','description'=>'Identifies information about the media or having to do with the medium in which information is stored.'),
            array('code'=>'NAME','name'=>'NAME','description'=>'A word or combination of words used to help identify an individual, title, or other item. More than one NAME line should be used for people who were known by multiple names.'),
            array('code'=>'NATI','name'=>'NATIONALITY','description'=>'The national heritage of an individual.'),
            array('code'=>'NATU','name'=>'NATURALIZATION','description'=>'The event of obtaining citizenship.'),
            array('code'=>'NCHI','name'=>'CHILDREN_COUNT','description'=>'The number of children that this person is known to be the parent of (all marriages) when subordinate to an individual, or that belong to this family when subordinate to a FAM_RECORD.'),
            array('code'=>'NICK','name'=>'NICKNAME','description'=>'A descriptive or familiar that is used instead of, or in addition to, one\'s proper name.'),
            array('code'=>'NMR','name'=>'MARRIAGE_COUNT','description'=>'The number of times this person has participated in a family as a spouse or parent.'),
            array('code'=>'NOTE','name'=>'NOTE','description'=>'Additional information provided by the submitter for understanding the enclosing data.'),
            array('code'=>'NPFX','name'=>'NAME_PREFIX','description'=>'Text which appears on a name line before the given and surname parts of a name. i.e. (Lt. Cmndr.) Joseph /Allen/ jr.'),
            array('code'=>'NSFX','name'=>'NAME_SUFFIX','description'=>'Text which appears on a name line after or behind the given and surname parts of a name. i.e. Lt. Cmndr. Joseph /Allen/ (jr.) In this example jr. is considered as the name suffix portion.'),
            array('code'=>'OBJE','name'=>'OBJECT','description'=>'Pertaining to a grouping of attributes used in describing something. Usually referring to the data required to represent a multimedia object, such an audio recording, a photograph of a person, or an image of a document.'),
            array('code'=>'OCCU','name'=>'OCCUPATION','description'=>'The type of work or profession of an individual.'),
            array('code'=>'ORDI','name'=>'ORDINANCE','description'=>'Pertaining to a religious ordinance in general.'),
            array('code'=>'ORDN','name'=>'ORDINATION','description'=>'A religious event of receiving authority to act in religious matters.'),
            array('code'=>'PAGE','name'=>'PAGE','description'=>'A number or description to identify where information can be found in a referenced work.'),
            array('code'=>'PEDI','name'=>'PEDIGREE','description'=>'Information pertaining to an individual to parent lineage chart.'),
            array('code'=>'PHON','name'=>'PHONE','description'=>'A unique number assigned to access a specific telephone.'),
            array('code'=>'PLAC','name'=>'PLACE','description'=>'A jurisdictional name to identify the place or location of an event.'),
            array('code'=>'POST','name'=>'POSTAL_CODE','description'=>'A code used by a postal service to identify an area to facilitate mail handling.'),
            array('code'=>'PROB','name'=>'PROBATE','description'=>'An event of judicial determination of the validity of a will. May indicate several related court activities over several dates.'),
            array('code'=>'PROP','name'=>'PROPERTY','description'=>'Pertaining to possessions such as real estate or other property of interest.'),
            array('code'=>'PUBL','name'=>'PUBLICATION','description'=>'Refers to when and/or were a work was published or created.'),
            array('code'=>'QUAY','name'=>'QUALITY_OF_DATA','description'=>'An assessment of the certainty of the evidence to support the conclusion drawn from evidence. Values: [0|1|2|3]'),
            array('code'=>'REFN','name'=>'REFERENCE','description'=>'A description or number used to identify an item for filing, storage, or other reference purposes.'),
            array('code'=>'RELA','name'=>'RELATIONSHIP','description'=>'A relationship value between the indicated contexts.'),
            array('code'=>'RELI','name'=>'RELIGION','description'=>'A religious denomination to which a person is affiliated or for which a record applies.'),
            array('code'=>'REPO','name'=>'REPOSITORY','description'=>'An institution or person that has the specified item as part of their collection(s).'),
            array('code'=>'RESI','name'=>'RESIDENCE','description'=>'The act of dwelling at an address for a period of time.'),
            array('code'=>'RESN','name'=>'RESTRICTION','description'=>'A processing indicator signifying access to information has been denied or otherwise restricted.'),
            array('code'=>'RETI','name'=>'RETIREMENT','description'=>'An event of exiting an occupational relationship with an employer after a qualifying time period.'),
            array('code'=>'RFN','name'=>'REC_FILE_NUMBER','description'=>'A permanent number assigned to a record that uniquely identifies it within a known file.'),
            array('code'=>'RIN','name'=>'REC_ID_NUMBER','description'=>'A number assigned to a record by an originating automated system that can be used by a receiving system to report results pertaining to that record.'),
            array('code'=>'ROLE','name'=>'ROLE','description'=>'A name given to a role played by an individual in connection with an event.'),
            array('code'=>'SEX','name'=>'SEX','description'=>'Indicates the sex of an individual--male or female.'),
            array('code'=>'SLGC','name'=>'SEALING_CHILD','description'=>'A religious event pertaining to the sealing of a child to his or her parents in an LDS temple ceremony.'),
            array('code'=>'SLGS','name'=>'SEALING_SPOUSE','description'=>'A religious event pertaining to the sealing of a husband and wife in an LDS temple ceremony.'),
            array('code'=>'SOUR','name'=>'SOURCE','description'=>'The initial or original material from which information was obtained.'),
            array('code'=>'SPFX','name'=>'SURN_PREFIX','description'=>'A name piece used as a non-indexing pre-part of a surname.'),
            array('code'=>'SSN','name'=>'SOC_SEC_NUMBER','description'=>'A number assigned by the United States Social Security Administration. Used for tax identification purposes.'),
            array('code'=>'STAE','name'=>'STATE','description'=>'A geographical division of a larger jurisdictional area, such as a State within the United States of America.'),
            array('code'=>'STAT','name'=>'STATUS','description'=>'An assessment of the state or condition of something.'),
            array('code'=>'SUBM','name'=>'SUBMITTER','description'=>'An individual or organization who contributes genealogical data to a file or transfers it to someone else.'),
            array('code'=>'SUBN','name'=>'SUBMISSION','description'=>'Pertains to a collection of data issued for processing.'),
            array('code'=>'SURN','name'=>'SURNAME','description'=>'A family name passed on or used by members of a family.'),
            array('code'=>'TEMP','name'=>'TEMPLE','description'=>'The name or code that represents the name OF a temple of the LDS Church.'),
            array('code'=>'TEXT','name'=>'TEXT','description'=>'The exact wording found in an original source document.'),
            array('code'=>'TIME','name'=>'TIME','description'=>'A time value in a 24-hour clock format, including hours, minutes, and optional seconds, separated by a colon (:). Fractions of seconds are shown in decimal notation.'),
            array('code'=>'TITL','name'=>'TITLE','description'=>'A description of a specific writing or other work, such as the title of a book when used in a source context, or a formal designation used by an individual in connection with positions of royalty or other social status, such as Grand Duke.'),
            array('code'=>'TRLR','name'=>'TRAILER','description'=>'At level 0, specifies the end of a GEDCOM transmission.'),
            array('code'=>'TYPE','name'=>'TYPE','description'=>'A further qualification to the meaning of the associated superior tag. The value does not have any computer processing reliability. It is more in the form of a short one or two word note that should be displayed any time the associated data is displayed.'),
            array('code'=>'VERS','name'=>'VERSION','description'=>'Indicates which version of a product, item, or publication is being used or referenced.'),
            array('code'=>'WIFE','name'=>'WIFE','description'=>'An individual in the role as a mother and/or married woman.'),
            array('code'=>'WILL','name'=>'WILL','description'=>'A legal document treated as an event, by which a person disposes of his or her estate, to take effect after death. The event date is the date the will was signed while the person was alive. (See also PROBate)'),
        ));

        //this message shown in your terminal after running db:seed command
        $this->command->info("Codes table seeded :)");
    }
}
